= Zeiterfassung für Gruppe XX

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Hannes |Jing |Shiyue |Ziyi |Meng |Nick |Meeting
|1  |420   |390   |450   |390     |400    |400    |60
|2  |690   |700  |900    |660    |700    |720    |60
|3  |1200  |…    |890  |…    |…    |1100    |30
|4  |…   |…    |…    |…    |…    |…    |…    
|5  |…   |…    |…    |…    |…    |…    |…    
|6  |…   |…    |…    |…    |…    |…    |…    
|7  |…   |…    |…    |…    |…    |…    |…    
|8  |…   |…    |…    |…    |…    |…    |…    
|9  |…   |…    |…    |…    |…    |…    |…    
|10  |…   |…    |…    |…    |…    |…    |…    
|11  |…   |…    |…    |…    |…    |…    |…    
|12  |…   |…    |…    |…    |…    |…    |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
